name: fitsplots
channels:
    - defaults
dependencies:
    - python=3.8.2
    - numpy=1.18.1
    - pandas=1.0.3
    - matplotlib=3.2.1-0
    - pytz=2020-1
    - configparser=5.0.0
    - requests=2.23.0
    - pyproj=2.6.0
    - scipy=1.4.1
